name = "ipfs"
description = "IPFS client library for Ada: CID, CAR, UnixFS, gateway client"
version = "0.1.0"

authors = ["Konstantin Khlopkov"]
maintainers = ["Konstantin Khlopkov <konstantin.khlopkov93@gmail.com>"]
maintainers-logins = ["kokhlo"]
licenses = "MIT"

tags = ["ipfs", "cid", "multihash", "car", "unixfs", "gateway", "distributed"]

project-files = ["ipfs.gpr"]
